[program:cebu-rooms-queue]
process_name=%(program_name)s_%(process_num)02d
directory=/var/www/cebu_rooms2
command=/usr/bin/php artisan queue:work database --queue=mail,realtime,default --sleep=3 --tries=3 --timeout=120 --max-time=3600
user=www-data
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=130
redirect_stderr=true
stdout_logfile=/var/www/cebu_rooms2/storage/logs/supervisor-queue.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[program:cebu-rooms-reverb]
directory=/var/www/cebu_rooms2
command=/usr/bin/php artisan reverb:start --host=127.0.0.1 --port=8080
user=www-data
numprocs=1
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stopwaitsecs=10
redirect_stderr=true
stdout_logfile=/var/www/cebu_rooms2/storage/logs/supervisor-reverb.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5

[group:cebu-rooms]
programs=cebu-rooms-queue,cebu-rooms-reverb
priority=999
